import { base } from "./base";

const en: base = {
    "LOGIN_TITLE": "Welcome to ISS",
    "LOGIN_ERROR_KEY": "Attention the autologin key is wrong.",
    "GET_KEY": "Get my key !",
    "KEY": "Autologin key",
    "GRANTED_ACCESS": "Give me access",
    "HEADER_HOME": "Home",
    "HEADER_SETTING": "Setting",
    "HEADER_MODULE": "Units",
    "HEADER_AGENDA": "Agenda",
    "HEADER_PROFIL": "Profile",
    "HEADER_HOME_ACTI": "Activity Details",
    "HEADER_HOME_PROJ": "Project Details",
    "HEADER_HOME_MARK": "Mark Details",
    "ACTI_AT": "From",
    "ACTI_UNTIL": "to",
    "ACTI_REGISTED": "Registered",
    "ACTI_ROOM": "Room",
    "ACTI_REGISTER": "Register",
    "ACTI_ALREADY_R": "Already register",
    "ACTI_ALREADY_U": "Already unregister",
    "ACTI_TITLE": "Title",
    "DECONNECT": "Logout",
    "ACTI": "Activities",
    "PROJ": "Projects",
    "NOTE": "Marks",
    "HISTO": "History",
    "EMPTY_ACTI": "No activities",
    "EMPTY_PROJ": "No projects",
    "EMPTY_NOTE": "No notes",
    "EMPTY_HISTO": "No history",
    "PROFIL_CREDIT": "Credits",
    "PROFIL_FIRSTNAME": "Firstname",
    "PROFIL_LASTNAME": "Lastname",
    "PROFIL_YEAR": "Year",
    "PROFIL_SEMETER": "Semeter",
    'PROFIL_PROMO': "Promo",
    "FR": "French",
    "EN": "English",
    "CONTINUE": "Continue",
    "BACK": "Back",
    "REGISTER": "register",
    "UNREGISTER": "unregister"
}

export default en;