import { base } from "./base";

const fr :base = {
    "LOGIN_TITLE": "Bienvenue sur ISS",
    "LOGIN_ERROR_KEY": "Attention la clef autologin est erroné.",
    "GET_KEY": "Get my key !",
    "KEY": "Clef autologin",
    "GRANTED_ACCESS": "Donne moi l'accés",
    "HEADER_HOME": "Accueil",
    "HEADER_SETTING": "Paramètre",
    "HEADER_MODULE": "Module",
    "HEADER_AGENDA": "Agenda",
    "HEADER_PROFIL": "Profil",
    "HEADER_HOME_ACTI": "Détail de l'activité",
    "HEADER_HOME_PROJ": "Détail du projet",
    "HEADER_HOME_MARK": "Détail de la note",
    "HEADER_PROFIL_MARKS": "Détail des notes",
    "ACTI_AT": "De",
    "ACTI_UNTIL": "À",
    "ACTI_REGISTED": "Inscrit",
    "ACTI_ROOM": "Salle",
    "ACTI_REGISTER": "S'inscrire",
    "ACTI_ALREADY_R": "Déjà inscrit",
    "ACTI_ALREADY_U": "Déjà désinscrit",
    "ACTI_TITLE": "Titre",
    "DECONNECT": "Déconnection",
    "GOTOTOP": "Remonter en haut de la page",
    "ACCESSIBILITY": "Accessibilité",
    "ACTI": "Activités",
    "PROJ": "Projets",
    "NOTE": "Notes",
    "HISTO": "Historique",
    "EMPTY_ACTI": "Aucune activités",
    "EMPTY_PROJ": "Aucun projets",
    "EMPTY_NOTE": "Aucune notes",
    "EMPTY_HISTO": "Aucun historique",
    "PROFIL_CREDIT": "Crédits",
    "PROFIL_FIRSTNAME": "Prénom",
    "PROFIL_LASTNAME": "Nom",
    "PROFIL_YEAR": "Année",
    "PROFIL_SEMETER": "Semestre",
    "PROFIL_PROMO": "Promo",
    "PROFIL_EMPTY_SEMESTER": "Sélectionner un semestre",
    "PROFIL_MARKS": "Notes",
    "PROFIL_TIME_AVERAGE": "Moyenne Netsoul pour la dernière semaine",
    "PROFIL_DETAIL_ALL_MARKS": "Toutes les notes",
    "PROFIL_DETAIL_ACTI": "Activité",
    "PROFIL_DETAIL_COMMENT": "Commentaire",
    "PROFIL_DETAIL_VALUE": "Note",
    "PROFIL_DETAIL_MARK": "Détails de la note",
    "PROFIL_DETAIL_EMPTY": "Aucune notes",
    "PROFIL_DETAIL_EMPTY_SELECT": "Aucune note sélectionnée",
    "FR": "Français",
    "EN": "Anglais",
    "CONTINUE": "Continuer",
    "BACK": "Retour",
    "REGISTER": "S'inscrire",
    "UNREGISTER": "Se désinscrire",
    "YES": "Oui",
    "NO": "Non"
}

export default fr;