import { base } from "./base";

const fr :base = {
    "LOGIN_TITLE": "Bienvenue sur ISS",
    "LOGIN_ERROR_KEY": "Attention la clef autologin est erroné.",
    "GET_KEY": "Get my key !",
    "KEY": "Clef autologin",
    "GRANTED_ACCESS": "Donne moi l'accés",
    "HEADER_HOME": "Accueil",
    "HEADER_SETTING": "Paramètre",
    "HEADER_MODULE": "Module",
    "HEADER_AGENDA": "Agenda",
    "HEADER_PROFIL": "Profil",
    "HEADER_HOME_ACTI": "Détail de l'activité",
    "HEADER_HOME_PROJ": "Détail du projet",
    "ACTI_AT": "De",
    "ACTI_UNTIL": "À",
    "ACTI_REGISTED": "Inscrit",
    "ACTI_ROOM": "Salle",
    "ACTI_REGISTER": "S'inscrire",
    "ACTI_ALREADY_R": "Déjà inscrit",
    "ACTI_ALREADY_U": "Déjà désinscrit",
    "DECONNECT": "Déconnection",
    "ACTI": "Activités",
    "PROJ": "Projets",
    "NOTE": "Notes",
    "HISTO": "Historique",
    "EMPTY_ACTI": "Aucune activités",
    "EMPTY_PROJ": "Aucun projets",
    "EMPTY_NOTE": "Aucune notes",
    "EMPTY_HISTO": "Aucun historique",
    "PROFIL_CREDIT": "Crédits",
    "PROFIL_FIRSTNAME": "Prénom",
    "PROFIL_LASTNAME": "Nom",
    "PROFIL_YEAR": "Année",
    "PROFIL_SEMETER": "Semestre",
    'PROFIL_PROMO': "Promo",
    "FR": "Français",
    "EN": "Anglais",
    "CONTINUE": "Continuer",
    "BACK": "Retour",
    "REGISTER": "S'inscrire",
    "UNREGISTER": "Se désinscrire",
    "YES": "Oui",
    "NO": "Non"
}

export default fr;